### ISSUE TITLE
[Tracking] DFX Wallet Canister integration (both local and on network)

### ISSUE THREAD

**Issue by hansl** [dfinity/sdk#1059]
There is a wallet implementation already, and we want to open source it and also use it as the base experience for developers who need to hold cycles and tokens on the IC.

There are multiple tasks associated with this project;

- [x] build the wallet canister WASM as part of DFX build (and in assets), similar to how we build the asset canister
- [x] ship the wallet canister WASM and DID (same as asset canister)
- [ ] On `dfx deploy`;
  - [ ] to create a canister, forward the call through the wallet canister
    - [ ] if there is a wallet associated with an identity, use it (even if it fails, then show error)
    - [ ] if there is no wallet canister associated with an identity;
      - [ ] on local, create a wallet canister and add a huge amount of cycles to it (using management canister `dev_create_canister_with_funds`)
    - [ ] on other networks, tell the user with probably a call to action
  - [ ] to install code, forward the call through the wallet canister (see above)
- [ ] add a new method to associate a wallet canister ID to an identity
- [ ] add a additional config flag when starting the replica [see bottom]

Flag:
``` 
{
    hypervisor: {
        create_funds_whitelist: "*"
    }
}
```
