### ISSUE TITLE
Release 0.6.15 checklist

### ISSUE THREAD

**Issue by lsgunnlsgunn** [dfinity/sdk#1181]
Here's a first attempt at putting a release issue on the project board:
- [x] Make the Go / No go call (Mon).
- [x] Build the release candidate **(Tue). completed Wed**
- [x] Review release spreadsheet (Wed). Posted on Slack https://docs.google.com/spreadsheets/d/1pIblGqIeqapzptOtDb4h0LjJKDFIYXRxJrX9VaphfjA/edit#gid=1192496749&range=1:1
- [ ] Draft doc changes and release notes based on the spreadsheet (Wednesday-Thursday usually, depending on the number and complexity of features and when they were available).
- [ ] Review main doc update PRs, if applicable. Depending on the number and complexity of features and when they were available, this could take more than a day or two, but we'll assume this have minimal user-facing features.
- [ ] Review and approve the "Update Release" PR (basically, release notes and files that include a reference to the version number).
- [ ] Promote release candidate to `latest`.
- [ ] Deploy updated doc site.
- [ ] Tag doc archive.
- [ ] Add a release description to the tagged `sdk` release and copy release notes to the release description.
- [ ] Announce the release on the forum and internal Slack channels.
