### ISSUE TITLE
[tracking] Mercury Funds

### ISSUE THREAD

**Issue by hansl** [dfinity/sdk#1207]
In order, what needs to happen:

- [x] release DFX with latest replica
- [x] update CDK-RS PR https://github.com/dfinity/cdk-rs/pull/36 to use DFX 0.6.15 (that has the latest replica). Tests should not be all green

The work to move from `create_canister` to `provisional_create_canister` is not blocked by a release, only the wallet + cdk is. 

Provisional call update is https://github.com/dfinity/sdk/pull/1168 but it fails on CI, need investigation.

Issues related to this:
- [x] https://github.com/dfinity/cdk-rs/issues/38
- [x] https://github.com/dfinity/wallet-rs/issues/7
- [x] dfx should allow users to add wallet canister ID to their identity. This is a 1-to-1 relationship where an identity can only have one wallet per network. https://github.com/dfinity/sdk/pull/1289
- [x] dfx should use `provisional_create_canister` on local, and use wallet's `create_canister` on any other network. https://github.com/dfinity/agent-rs/pull/89 https://github.com/dfinity/sdk/pull/1233
- [x] https://github.com/dfinity/agent-rs/pull/83
- [x] update to new public spec api https://github.com/dfinity/sdk/issues/1248
