### ISSUE TITLE
Address feedback from https://brson.github.io/2021/01/30/dfinity-impressions

### ISSUE THREAD

**Issue by p-shahi** [dfinity/sdk#1351]
- [ ]  https://github.com/dfinity/sdk/issues/1352 sdk install script upkeep
- [x] https://github.com/dfinity/sdk/issues/1353 license agreement
- [ ] https://github.com/dfinity/sdk/issues/1354 uninstall script should report to user what it is doing
- [x] https://github.com/dfinity/sdk/issues/1355 dfx not added to $PATH on Linux
- [ ] https://github.com/dfinity/sdk/issues/1356 CTL+C on license prompt should return to original shell.
- [ ] https://github.com/dfinity/sdk/issues/1357 Every message directed to the user must go though a common interface that is thread-safe.
- [ ] https://github.com/dfinity/sdk/issues/1358 Remove all Unicode spinners.
- [x] https://github.com/dfinity/sdk/issues/1359 no more npm vulnerabilities
- [x] https://github.com/dfinity/sdk/issues/1360 fix confusing dfx upgrade behavior
- [x] https://github.com/dfinity/sdk/issues/1361 Remove multiple prints of the dfinity logo welcome banner.
- [x] https://github.com/dfinity/sdk/issues/1362 dfx logo looks terrible if not output on 256 color terminal 
- [x] https://github.com/dfinity/sdk/issues/1363 Remove suggestive error messages that may lead to ambiguity.
- [x] https://github.com/dfinity/sdk/issues/1364 Sanitize, prettyify, and make replica/emulator log output meaningful friendly
- [x] https://github.com/dfinity/sdk/issues/1365 remove references to wallet from docs
- [x] https://github.com/dfinity/sdk/issues/1366 replica errors with content type text/html should be displayed as text
- [x] https://github.com/dfinity/sdk/issues/1367 dfx canister call with canister id instead of canister name results in candid error
- [x] https://github.com/dfinity/docs/pull/332 Fix/Improve doc-related items:
** Added a placeholder DFX_INSTALLATION_ROOT envar
** Added a PATH section to the newcomers doc
** Removed rudimentary details about opening a new terminal window or tab
** Removed the reference to the ic-projects working folder
** Navigating to the project directory is now its own step
** Added querying canister ID as a task
** Added package.json example

**Comment by sesi200** [comment]
Closing as we don't use GH issues to track such things anymore.
