### ISSUE TITLE
Split JavaScript Agent in its own repo

### ISSUE THREAD

**Issue by hansl** [dfinity/sdk#958]
Statuses:
* 2020-09-02: Both PRs below ready for review and requsted from @hansl. [e2e/nix] is (I think) the only jobs broken, which I started digging into in [rm-agent-js-build](https://github.com/dfinity-lab/sdk/pull/988). But I need to pause and work on #989 today w/ @stanleygjones direction.
* 2020-08-31: Spent a lot of time Thursday, Friday wrestling with trying to get nix/hydra to build the lerna parts of [dfinity-lab/agent-js](https://github.com/dfinity-lab/agent-js/) to no avail. I synced with Hans this morning, and we decided to not use lerna for now, since it's not strictly needed. At least initially, we don't need this to be a monorepo of many packages. We only *need* it to be a home for the `@dfinity/agent` package. Next: Remove lerna and see if that makes it ez to pull this in from [sdk nix](https://github.com/dfinity-lab/sdk/pull/966).

---

Pull Requests:
* sdk: https://github.com/dfinity-lab/sdk/pull/981
* agent-js: (PR is master -> empty, just for code review) https://github.com/dfinity-lab/agent-js/pull/11

---

# Subtasks

## In Progress

This includes (might be out of order, also maintained by @gobengo):

- [x] use npm and lerna for managing multiple packages + versions
- [x] copy the agent code from dfinity-lab/sdk to a package in dfinity-lab/agent-js
  - [x] Later, we'll want to do another pass to copypsta any changes to the agent that happen between now and when we're ready to do call this repo the source of truth. In service of this, it may be useful to enumerate any deviations between what we want to publish in this repo and what's happening in the sdk until now. So far the only differences are:
    - None, but I'm asking @hansl if I should maybe remove `INTERNAL.adoc` and `default.nix`
  - [x] Later, we'll need to remove the js agent from the sdk, since it should now only live here
- [x] setup GitHub Workflows for tests of the new repo
- [x] setup GitHub Workflows to lint git commit messages of new repo
- [x] setup a local git commit hook to ensure linted commit messages
  - [x] remove this. We don't need to enforce this on every single commit. @hansl says to only enforce it in PR titles, then ensure all commits to master are squashed PRs whose titles are conventionalcommit titles. (bengo: I kinda like having this so punting on removing this until the end, if i must).
- [x] Add Mergeify config file so it works ([first working](https://github.com/dfinity-lab/agent-js/pull/3))
- [x] Add conventional PR checking like in agent-rust
- [x] move the bootstrap code from dfinity-lab/sdk to a package in [dfinity-lab/agent-js](https://github.com/dfinity-lab/agent-js/): https://github.com/dfinity-lab/agent-js/tree/master/packages/bootstrap
  - We do **not** need to preserve git commit history for any code
- [x] updating sdk nix rules to use @dfinity/agent
  - in doing this, we realized it is very hard for our nix to build this repo if it uses lerna, so we decided to not use it for now 
- [x] update `js_agent_version` variable in `dfx new` to reflect a github link instead of the dfx version
- [x] If possible, have the GitHub Actions check to make sure we use https://www.conventionalcommits.org/en/v1.0.0/
- [x] Add first draft of GitHub workflow to monorepo to do `lerna publish` to release to npm
  - [x] do final pass of how we want this to work and drive releases

## Maybe

bengo proposes punting these incomplete tasks to followup issues:

- make sure the new repo has README.md for the repo, a CONTRIBUTING.md, and other high level repo stuff.
  * [issue for CONTRIBUTING.md](https://github.com/dfinity-lab/agent-js/issues/21)
- [Factor out candid/idl stuff from agent package into a candid js package.](https://github.com/dfinity-lab/agent-js/issues/20)
- [Move node e2e tests into this repo from sdk. @hansl Says the only reason sdk wants a direct dependency on agent is for those e2e tests. If we move them here, sdk will only have a transitive dependency to agent via bootstrap](https://github.com/dfinity-lab/agent-js/issues/16)
